// <auto-generated />
using System;
using CvSU.Ais.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CvSU.Ais.Infrastructure.Migrations
{
    [DbContext(typeof(AisDbContext))]
    partial class AisDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CvSU.Ais.Infrastructure.Persistence.BudgetLedgerRow", b =>
                {
                    b.Property<long>("LedgerSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ledger_seq");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LedgerSeq"));

                    b.Property<string>("AllotmentId")
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("allotment_id");

                    b.Property<string>("AppropriationId")
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("appropriation_id");

                    b.Property<decimal>("Credit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("credit");

                    b.Property<decimal>("Debit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("debit");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("entry_type");

                    b.Property<string>("ExpenseClass")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("expense_class");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("integer")
                        .HasColumnName("fiscal_year");

                    b.Property<string>("FundingSourceCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("funding_source_code");

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("location_code");

                    b.Property<string>("ObjectAccountCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("object_account_code");

                    b.Property<string>("PapCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("pap_code");

                    b.Property<DateOnly>("PostingDate")
                        .HasColumnType("date")
                        .HasColumnName("posting_date");

                    b.Property<string>("VoucherDoctype")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("voucher_doctype");

                    b.Property<string>("VoucherNo")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("voucher_no");

                    b.HasKey("LedgerSeq")
                        .HasName("pk_budget_ledger_entry");

                    b.HasIndex("FundingSourceCode")
                        .HasDatabaseName("ix_budget_ledger_entry_funding_source_code");

                    b.HasIndex("AllotmentId", "EntryType")
                        .HasDatabaseName("ix_budget_ledger_entry_allotment_id_entry_type");

                    b.HasIndex("FiscalYear", "ExpenseClass")
                        .HasDatabaseName("ix_budget_ledger_entry_fiscal_year_expense_class");

                    b.HasIndex("VoucherDoctype", "VoucherNo")
                        .HasDatabaseName("ix_budget_ledger_entry_voucher_doctype_voucher_no");

                    b.HasIndex("FiscalYear", "FundingSourceCode", "ExpenseClass")
                        .HasDatabaseName("ix_budget_ledger_entry_fiscal_year_funding_source_code_expense");

                    b.ToTable("budget_ledger_entry", null, t =>
                        {
                            t.HasCheckConstraint("ck_ble_credit_nonneg", "credit >= 0");

                            t.HasCheckConstraint("ck_ble_debit_nonneg", "debit >= 0");

                            t.HasCheckConstraint("ck_ble_single_sided", "NOT (debit > 0 AND credit > 0)");
                        });
                });

            modelBuilder.Entity("CvSU.Ais.Infrastructure.Persistence.DisbursementVoucherRow", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("name");

                    b.Property<bool>("AccountantSigned")
                        .HasColumnType("boolean")
                        .HasColumnName("accountant_signed");

                    b.Property<DateTime?>("AccountantSignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accountant_signed_at");

                    b.Property<string>("AccountantSignedBy")
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("accountant_signed_by");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("approved_by");

                    b.Property<string>("ApprovedForPaymentBy")
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("approved_for_payment_by");

                    b.Property<bool>("BudgetCertified")
                        .HasColumnType("boolean")
                        .HasColumnName("budget_certified");

                    b.Property<DateTime?>("BudgetCertifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("budget_certified_at");

                    b.Property<string>("BudgetCertifiedBy")
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("budget_certified_by");

                    b.Property<string>("ControlNumber")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("control_number");

                    b.Property<string>("DvType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("dv_type");

                    b.Property<string>("Encoder")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("encoder");

                    b.Property<bool>("EndUserConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("end_user_confirmed");

                    b.Property<DateTime?>("EndUserConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_user_confirmed_at");

                    b.Property<string>("EndUserConfirmedBy")
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("end_user_confirmed_by");

                    b.Property<string>("ExpenseClass")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("expense_class");

                    b.Property<string>("FundingSourceCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("funding_source_code");

                    b.Property<bool>("InternalAuditConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("internal_audit_confirmed");

                    b.Property<DateTime?>("InternalAuditConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("internal_audit_confirmed_at");

                    b.Property<string>("InternalAuditConfirmedBy")
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("internal_audit_confirmed_by");

                    b.Property<string>("Lifecycle")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("lifecycle");

                    b.Property<string>("LocationCode")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("location_code");

                    b.Property<string>("ObjectAccountCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("object_account_code");

                    b.Property<string>("PapCode")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("pap_code");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("payment_method");

                    b.Property<string>("PaymentReference")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("payment_reference");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<bool>("SupplyPropertySignedOff")
                        .HasColumnType("boolean")
                        .HasColumnName("supply_property_signed_off");

                    b.Property<DateTime?>("SupplyPropertySignedOffAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("supply_property_signed_off_at");

                    b.Property<string>("SupplyPropertySignedOffBy")
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("supply_property_signed_off_by");

                    b.Property<decimal>("TaxWithheld")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("tax_withheld");

                    b.HasKey("Name")
                        .HasName("pk_disbursement_voucher");

                    b.HasIndex("ControlNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_disbursement_voucher_control_number")
                        .HasFilter("control_number IS NOT NULL");

                    b.HasIndex("FundingSourceCode")
                        .HasDatabaseName("ix_disbursement_voucher_funding_source_code");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_disbursement_voucher_status");

                    b.HasIndex("PaymentMethod", "PaymentReference")
                        .IsUnique()
                        .HasDatabaseName("ix_disbursement_voucher_payment_method_payment_reference")
                        .HasFilter("payment_reference IS NOT NULL");

                    b.ToTable("disbursement_voucher", (string)null);
                });

            modelBuilder.Entity("CvSU.Ais.Infrastructure.Persistence.FundingSourceRow", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<string>("ClusterCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("cluster_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Code")
                        .HasName("pk_funding_source");

                    b.ToTable("funding_source", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "01101101",
                            ClusterCode = "01",
                            Name = "Regular Agency Fund"
                        },
                        new
                        {
                            Code = "05101101",
                            ClusterCode = "05",
                            Name = "Internally Generated Funds (STF)"
                        });
                });

            modelBuilder.Entity("CvSU.Ais.Infrastructure.Persistence.GeneralLedgerRow", b =>
                {
                    b.Property<long>("LedgerSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ledger_seq");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LedgerSeq"));

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("account");

                    b.Property<decimal>("Credit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("credit");

                    b.Property<decimal>("Debit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("debit");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("integer")
                        .HasColumnName("fiscal_year");

                    b.Property<DateOnly>("PostingDate")
                        .HasColumnType("date")
                        .HasColumnName("posting_date");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.Property<string>("VoucherDoctype")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("voucher_doctype");

                    b.Property<string>("VoucherNo")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("voucher_no");

                    b.HasKey("LedgerSeq")
                        .HasName("pk_gl_entry");

                    b.HasIndex("FiscalYear", "PostingDate")
                        .HasDatabaseName("ix_gl_entry_fiscal_year_posting_date");

                    b.HasIndex("VoucherDoctype", "VoucherNo")
                        .HasDatabaseName("ix_gl_entry_voucher_doctype_voucher_no");

                    b.ToTable("gl_entry", null, t =>
                        {
                            t.HasCheckConstraint("ck_gl_credit_nonneg", "credit >= 0");

                            t.HasCheckConstraint("ck_gl_debit_nonneg", "debit >= 0");

                            t.HasCheckConstraint("ck_gl_single_sided", "NOT (debit > 0 AND credit > 0)");
                        });
                });

            modelBuilder.Entity("CvSU.Ais.Infrastructure.Persistence.OfficialReceiptRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount_paid");

                    b.Property<string>("CostCenter")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("cost_center");

                    b.Property<string>("CreditAccount")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("credit_account");

                    b.Property<string>("FeeType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("fee_type");

                    b.Property<string>("FundCluster")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("fund_cluster");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTimeOffset?>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("mode");

                    b.Property<string>("OrNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("or_number");

                    b.Property<string>("PaidToAccount")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("paid_to_account");

                    b.Property<string>("Payor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("payor");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_official_receipt");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_official_receipt_idempotency_key");

                    b.HasIndex("OrNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_official_receipt_or_number");

                    b.ToTable("official_receipt", (string)null);
                });

            modelBuilder.Entity("CvSU.Ais.Infrastructure.Persistence.VoucherCounter", b =>
                {
                    b.Property<string>("Series")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("series");

                    b.Property<long>("Current")
                        .HasColumnType("bigint")
                        .HasColumnName("current");

                    b.HasKey("Series")
                        .HasName("pk_voucher_counter");

                    b.ToTable("voucher_counter", (string)null);
                });

            modelBuilder.Entity("CvSU.Ais.Infrastructure.Persistence.BudgetLedgerRow", b =>
                {
                    b.HasOne("CvSU.Ais.Infrastructure.Persistence.FundingSourceRow", null)
                        .WithMany()
                        .HasForeignKey("FundingSourceCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_budget_ledger_entry_funding_source_funding_source_code");
                });

            modelBuilder.Entity("CvSU.Ais.Infrastructure.Persistence.DisbursementVoucherRow", b =>
                {
                    b.HasOne("CvSU.Ais.Infrastructure.Persistence.FundingSourceRow", null)
                        .WithMany()
                        .HasForeignKey("FundingSourceCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_disbursement_voucher_funding_source_funding_source_code");
                });
#pragma warning restore 612, 618
        }
    }
}
