// <auto-generated />
using System;
using CvSU.Ais.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CvSU.Ais.Infrastructure.Migrations
{
    [DbContext(typeof(AisDbContext))]
    partial class AisDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CvSU.Ais.Infrastructure.Persistence.BudgetLedgerRow", b =>
                {
                    b.Property<long>("LedgerSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LedgerSeq"));

                    b.Property<string>("AllotmentId")
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.Property<string>("AppropriationId")
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.Property<decimal>("Credit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Debit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ExpenseClass")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("integer");

                    b.Property<string>("FundingSourceCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ObjectAccountCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PapCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateOnly>("PostingDate")
                        .HasColumnType("date");

                    b.Property<string>("VoucherDoctype")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.Property<string>("VoucherNo")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.HasKey("LedgerSeq");

                    b.HasIndex("FundingSourceCode");

                    b.HasIndex("AllotmentId", "EntryType");

                    b.HasIndex("FiscalYear", "ExpenseClass");

                    b.HasIndex("VoucherDoctype", "VoucherNo");

                    b.HasIndex("FiscalYear", "FundingSourceCode", "ExpenseClass");

                    b.ToTable("budget_ledger_entry", null, t =>
                        {
                            t.HasCheckConstraint("ck_ble_credit_nonneg", "credit >= 0");

                            t.HasCheckConstraint("ck_ble_debit_nonneg", "debit >= 0");

                            t.HasCheckConstraint("ck_ble_single_sided", "NOT (debit > 0 AND credit > 0)");
                        });
                });

            modelBuilder.Entity("CvSU.Ais.Infrastructure.Persistence.FundingSourceRow", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ClusterCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Code");

                    b.ToTable("funding_source", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "01101101",
                            ClusterCode = "01",
                            Name = "Regular Agency Fund"
                        },
                        new
                        {
                            Code = "05101101",
                            ClusterCode = "05",
                            Name = "Internally Generated Funds (STF)"
                        });
                });

            modelBuilder.Entity("CvSU.Ais.Infrastructure.Persistence.GeneralLedgerRow", b =>
                {
                    b.Property<long>("LedgerSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LedgerSeq"));

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("Credit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Debit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("PostingDate")
                        .HasColumnType("date");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<string>("VoucherDoctype")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.Property<string>("VoucherNo")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.HasKey("LedgerSeq");

                    b.HasIndex("FiscalYear", "PostingDate");

                    b.HasIndex("VoucherDoctype", "VoucherNo");

                    b.ToTable("gl_entry", null, t =>
                        {
                            t.HasCheckConstraint("ck_gl_credit_nonneg", "credit >= 0");

                            t.HasCheckConstraint("ck_gl_debit_nonneg", "debit >= 0");

                            t.HasCheckConstraint("ck_gl_single_sided", "NOT (debit > 0 AND credit > 0)");
                        });
                });

            modelBuilder.Entity("CvSU.Ais.Infrastructure.Persistence.VoucherCounter", b =>
                {
                    b.Property<string>("Series")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("Current")
                        .HasColumnType("bigint");

                    b.HasKey("Series");

                    b.ToTable("voucher_counter", (string)null);
                });

            modelBuilder.Entity("CvSU.Ais.Infrastructure.Persistence.BudgetLedgerRow", b =>
                {
                    b.HasOne("CvSU.Ais.Infrastructure.Persistence.FundingSourceRow", null)
                        .WithMany()
                        .HasForeignKey("FundingSourceCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
